import AxiosService from "@common/utils/axios";

const url = {
  getCategories: "categories",
};

const fetchCommon = {
  async getCategories() {
    // const response = await AxiosService.get(url.getCategories);
    return {
      data: [
        {
          _id: "174",
          name: "Girl",
          parent: "/",
          level: 1,
          path: "/girl",
          slug: "girl",
          children: [
            {
              _id: "251",
              name: "Clothing",
              parent: "/girl",
              level: 2,
              path: "/girl/clothing",
              slug: "clothing",
              children: [
                {
                  _id: "320",
                  name: "Cardigans",
                  parent: "/girl/clothing",
                  level: 3,
                  path: "/girl/clothing/cardigans",
                  slug: "cardigans",
                },
                {
                  _id: "192",
                  name: "Coats,jackets",
                  parent: "/girl/clothing",
                  level: 3,
                  path: "/girl/clothing/coats",
                  slug: "coats",
                },
                {
                  _id: "269",
                  name: "Dresses",
                  parent: "/girl/clothing",
                  level: 3,
                  path: "/girl/clothing/dresses",
                  slug: "dresses",
                },
                {
                  _id: "292",
                  name: "Jeans",
                  parent: "/girl/clothing",
                  level: 3,
                  path: "/girl/clothing/jeans",
                  slug: "jeans",
                },
                {
                  _id: "325",
                  name: "Jumpsuits",
                  parent: "/girl/clothing",
                  level: 3,
                  path: "/girl/clothing/jumpsuits",
                  slug: "jumpsuits",
                },
                {
                  _id: "9514",
                  name: "Leggings",
                  parent: "/girl/clothing",
                  level: 3,
                  path: "/girl/clothing/leggings",
                  slug: "leggings",
                },
                {
                  _id: "317",
                  name: "Overalls",
                  parent: "/girl/clothing",
                  level: 3,
                  path: "/girl/clothing/overalls",
                  slug: "overalls",
                },
                {
                  _id: "234",
                  name: "Pajamas",
                  parent: "/girl/clothing",
                  level: 3,
                  path: "/girl/clothing/pajamas",
                  slug: "pajamas",
                },
                {
                  _id: "299",
                  name: "Pants",
                  parent: "/girl/clothing",
                  level: 3,
                  path: "/girl/clothing/pants",
                  slug: "pants",
                },
                {
                  _id: "287",
                  name: "Shirts, Blouses",
                  parent: "/girl/clothing",
                  level: 3,
                  path: "/girl/clothing/shirts-blouses",
                  slug: "shirts-blouses",
                },
                {
                  _id: "328",
                  name: "Shorts",
                  parent: "/girl/clothing",
                  level: 3,
                  path: "/girl/clothing/shorts",
                  slug: "shorts",
                },
                {
                  _id: "260",
                  name: "Ski",
                  parent: "/girl/clothing",
                  level: 3,
                  path: "/girl/clothing/ski",
                  slug: "ski",
                },
                {
                  _id: "212",
                  name: "Skirts",
                  parent: "/girl/clothing",
                  level: 3,
                  path: "/girl/clothing/skirts",
                  slug: "skirts",
                },
                {
                  _id: "9534",
                  name: "Socks",
                  parent: "/girl/clothing",
                  level: 3,
                  path: "/girl/clothing/socks",
                  slug: "socks",
                },
                {
                  _id: "8862",
                  name: "Sweaters",
                  parent: "/girl/clothing",
                  level: 3,
                  path: "/girl/clothing/sweaters",
                  slug: "sweaters",
                },
                {
                  _id: "314",
                  name: "Sweatpants",
                  parent: "/girl/clothing",
                  level: 3,
                  path: "/girl/clothing/sweatpants",
                  slug: "sweatpants",
                },
                {
                  _id: "309",
                  name: "Sweatshirts",
                  parent: "/girl/clothing",
                  level: 3,
                  path: "/girl/clothing/sweatshirts",
                  slug: "sweatshirts",
                },
                {
                  _id: "227",
                  name: "Swimsuits",
                  parent: "/girl/clothing",
                  level: 3,
                  path: "/girl/clothing/swimsuits",
                  slug: "swimsuits",
                },
                {
                  _id: "219",
                  name: "T-shirts",
                  parent: "/girl/clothing",
                  level: 3,
                  path: "/girl/clothing/t-shirts",
                  slug: "t-shirts",
                },
                {
                  _id: "9535",
                  name: "Tights",
                  parent: "/girl/clothing",
                  level: 3,
                  path: "/girl/clothing/tights",
                  slug: "tights",
                },
                {
                  _id: "282",
                  name: "Underwear",
                  parent: "/girl/clothing",
                  level: 3,
                  path: "/girl/clothing/underwear",
                  slug: "underwear",
                },
              ],
            },
            {
              _id: "175",
              name: "Shoes",
              parent: "/girl",
              level: 2,
              path: "/girl/shoes",
              slug: "shoes",
              children: [
                {
                  _id: "177",
                  name: "Boots",
                  parent: "/girl/shoes",
                  level: 3,
                  path: "/girl/shoes/boots",
                  slug: "boots",
                },
                {
                  _id: "179",
                  name: "Boots, Booties",
                  parent: "/girl/shoes",
                  level: 3,
                  path: "/girl/shoes/boots-booties",
                  slug: "boots-booties",
                },
                {
                  _id: "185",
                  name: "Derbies",
                  parent: "/girl/shoes",
                  level: 3,
                  path: "/girl/shoes/derbies",
                  slug: "derbies",
                },
                {
                  _id: "184",
                  name: "Flats",
                  parent: "/girl/shoes",
                  level: 3,
                  path: "/girl/shoes/flats",
                  slug: "flats",
                },
                {
                  _id: "180",
                  name: "Flip-Flops",
                  parent: "/girl/shoes",
                  level: 3,
                  path: "/girl/shoes/flip-flops",
                  slug: "flip-flops",
                },
                {
                  _id: "189",
                  name: "Loafers",
                  parent: "/girl/shoes",
                  level: 3,
                  path: "/girl/shoes/loafers",
                  slug: "loafers",
                },
                {
                  _id: "183",
                  name: "Rain boots",
                  parent: "/girl/shoes",
                  level: 3,
                  path: "/girl/shoes/rain-boots",
                  slug: "rain-boots",
                },
                {
                  _id: "186",
                  name: "Sandals",
                  parent: "/girl/shoes",
                  level: 3,
                  path: "/girl/shoes/sandals",
                  slug: "sandals",
                },
                {
                  _id: "188",
                  name: "Slippers",
                  parent: "/girl/shoes",
                  level: 3,
                  path: "/girl/shoes/slippers",
                  slug: "slippers",
                },
                {
                  _id: "182",
                  name: "Sneakers",
                  parent: "/girl/shoes",
                  level: 3,
                  path: "/girl/shoes/sneakers",
                  slug: "sneakers",
                },
              ],
            },
            {
              _id: "240",
              name: "Accessories",
              parent: "/girl",
              level: 2,
              path: "/girl/accessories",
              slug: "accessories",
              children: [
                {
                  _id: "245",
                  name: "Backpacks",
                  parent: "/girl/accessories",
                  level: 3,
                  path: "/girl/accessories/backpacks",
                  slug: "backpacks",
                },
                {
                  _id: "248",
                  name: "Bags",
                  parent: "/girl/accessories",
                  level: 3,
                  path: "/girl/accessories/bags",
                  slug: "bags",
                },
                {
                  _id: "246",
                  name: "Beanies, Fur Hats, Balaclavas",
                  parent: "/girl/accessories",
                  level: 3,
                  path: "/girl/accessories/beanies-fur-hats-balaclavas",
                  slug: "beanies-fur-hats-balaclavas",
                },
                {
                  _id: "242",
                  name: "Belts, Suspenders",
                  parent: "/girl/accessories",
                  level: 3,
                  path: "/girl/accessories/belts-suspenders",
                  slug: "belts-suspenders",
                },
                {
                  _id: "253",
                  name: "Collars, Bows",
                  parent: "/girl/accessories",
                  level: 3,
                  path: "/girl/accessories/collars-bows",
                  slug: "collars-bows",
                },
                {
                  _id: "249",
                  name: "Gloves Mittens",
                  parent: "/girl/accessories",
                  level: 3,
                  path: "/girl/accessories/gloves-mittens",
                  slug: "gloves-mittens",
                },
                {
                  _id: "241",
                  name: "Hair Accessories",
                  parent: "/girl/accessories",
                  level: 3,
                  path: "/girl/accessories/hair-accessories",
                  slug: "hair-accessories",
                },
                {
                  _id: "258",
                  name: "Hats, Caps",
                  parent: "/girl/accessories",
                  level: 3,
                  path: "/girl/accessories/hats-and-beret",
                  slug: "hats-and-beret",
                },
                {
                  _id: "259",
                  name: "Jewelry",
                  parent: "/girl/accessories",
                  level: 3,
                  path: "/girl/accessories/jewelry",
                  slug: "jewelry",
                },
                {
                  _id: "247",
                  name: "Scarves Headscarves",
                  parent: "/girl/accessories",
                  level: 3,
                  path: "/girl/accessories/scarves-headscarves",
                  slug: "scarves-headscarves",
                },
                {
                  _id: "255",
                  name: "Schoolbags",
                  parent: "/girl/accessories",
                  level: 3,
                  path: "/girl/accessories/schoolbags",
                  slug: "schoolbags",
                },
                {
                  _id: "243",
                  name: "Sunglasses",
                  parent: "/girl/accessories",
                  level: 3,
                  path: "/girl/accessories/sunglasses",
                  slug: "sunglasses",
                },
              ],
            },
          ],
        },
        {
          _id: "343",
          name: "Boy",
          parent: "/",
          level: 1,
          path: "/boy",
          slug: "boy",
          children: [
            {
              _id: "256",
              name: "Clothing",
              parent: "/boy",
              level: 2,
              path: "/boy/clothing",
              slug: "clothing",
              children: [
                {
                  _id: "404",
                  name: "Cardigans",
                  parent: "/boy/clothing",
                  level: 3,
                  path: "/boy/clothing/cardigans",
                  slug: "cardigans",
                },
                {
                  _id: "346",
                  name: "Coats, Jackets",
                  parent: "/boy/clothing",
                  level: 3,
                  path: "/boy/clothing/coats-jackets",
                  slug: "coats-jackets",
                },
                {
                  _id: "462",
                  name: "Jeans",
                  parent: "/boy/clothing",
                  level: 3,
                  path: "/boy/clothing/jeans",
                  slug: "jeans",
                },
                {
                  _id: "476",
                  name: "Overalls",
                  parent: "/boy/clothing",
                  level: 3,
                  path: "/boy/clothing/overalls",
                  slug: "overalls",
                },
                {
                  _id: "380",
                  name: "Pajamas",
                  parent: "/boy/clothing",
                  level: 3,
                  path: "/boy/clothing/pajamas",
                  slug: "pajamas",
                },
                {
                  _id: "452",
                  name: "Pants",
                  parent: "/boy/clothing",
                  level: 3,
                  path: "/boy/clothing/pants",
                  slug: "pants",
                },
                {
                  _id: "423",
                  name: "Shirts and Blouses",
                  parent: "/boy/clothing",
                  level: 3,
                  path: "/boy/clothing/shirts-and-blouses",
                  slug: "shirts-and-blouses",
                },
                {
                  _id: "471",
                  name: "Shorts",
                  parent: "/boy/clothing",
                  level: 3,
                  path: "/boy/clothing/shorts",
                  slug: "shorts",
                },
                {
                  _id: "410",
                  name: "Ski",
                  parent: "/boy/clothing",
                  level: 3,
                  path: "/boy/clothing/ski",
                  slug: "ski",
                },
                {
                  _id: "9517",
                  name: "Socks-boys",
                  parent: "/boy/clothing",
                  level: 3,
                  path: "/boy/clothing/socks-boys",
                  slug: "socks-boys",
                },
                {
                  _id: "418",
                  name: "Suits",
                  parent: "/boy/clothing",
                  level: 3,
                  path: "/boy/clothing/suits",
                  slug: "suits",
                },
                {
                  _id: "8868",
                  name: "Sweaters",
                  parent: "/boy/clothing",
                  level: 3,
                  path: "/boy/clothing/sweaters",
                  slug: "sweaters",
                },
                {
                  _id: "427",
                  name: "Sweatpants",
                  parent: "/boy/clothing",
                  level: 3,
                  path: "/boy/clothing/sweatpants",
                  slug: "sweatpants",
                },
                {
                  _id: "393",
                  name: "Sweatshirts",
                  parent: "/boy/clothing",
                  level: 3,
                  path: "/boy/clothing/sweatshirts",
                  slug: "sweatshirts",
                },
                {
                  _id: "398",
                  name: "Swimsuits",
                  parent: "/boy/clothing",
                  level: 3,
                  path: "/boy/clothing/swimsuits",
                  slug: "swimsuits",
                },
                {
                  _id: "385",
                  name: "T-shirts",
                  parent: "/boy/clothing",
                  level: 3,
                  path: "/boy/clothing/t-shirts",
                  slug: "t-shirts",
                },
                {
                  _id: "430",
                  name: "Underwear",
                  parent: "/boy/clothing",
                  level: 3,
                  path: "/boy/clothing/underwear",
                  slug: "underwear",
                },
              ],
            },
            {
              _id: "364",
              name: "Shoes",
              parent: "/boy",
              level: 2,
              path: "/boy/shoes",
              slug: "shoes",
              children: [
                {
                  _id: "365",
                  name: "Boot, Booties",
                  parent: "/boy/shoes",
                  level: 3,
                  path: "/boy/shoes/boots-booties",
                  slug: "boots-booties",
                },
                {
                  _id: "367",
                  name: "Boots",
                  parent: "/boy/shoes",
                  level: 3,
                  path: "/boy/shoes/boots",
                  slug: "boots",
                },
                {
                  _id: "372",
                  name: "Derbies",
                  parent: "/boy/shoes",
                  level: 3,
                  path: "/boy/shoes/derbies",
                  slug: "derbies",
                },
                {
                  _id: "368",
                  name: "Flip-Flops",
                  parent: "/boy/shoes",
                  level: 3,
                  path: "/boy/shoes/flip-flops",
                  slug: "flip-flops",
                },
                {
                  _id: "371",
                  name: "Rain-boots",
                  parent: "/boy/shoes",
                  level: 3,
                  path: "/boy/shoes/rain-boots",
                  slug: "rain-boots",
                },
                {
                  _id: "374",
                  name: "Sandals",
                  parent: "/boy/shoes",
                  level: 3,
                  path: "/boy/shoes/sandals",
                  slug: "sandals",
                },
                {
                  _id: "375",
                  name: "Slippers",
                  parent: "/boy/shoes",
                  level: 3,
                  path: "/boy/shoes/slippers",
                  slug: "slippers",
                },
                {
                  _id: "370",
                  name: "Sneakers",
                  parent: "/boy/shoes",
                  level: 3,
                  path: "/boy/shoes/sneakers",
                  slug: "sneakers",
                },
              ],
            },
            {
              _id: "433",
              name: "Accessories",
              parent: "/boy",
              level: 2,
              path: "/boy/accessories",
              slug: "accessories",
              children: [
                {
                  _id: "436",
                  name: "Backpacks",
                  parent: "/boy/accessories",
                  level: 3,
                  path: "/boy/accessories/backpacks",
                  slug: "backpacks",
                },
                {
                  _id: "445",
                  name: "Bags",
                  parent: "/boy/accessories",
                  level: 3,
                  path: "/boy/accessories/bags",
                  slug: "bags",
                },
                {
                  _id: "437",
                  name: "Beanies, Fur Hats, Balaclavas",
                  parent: "/boy/accessories",
                  level: 3,
                  path: "/boy/accessories/beanies-fur-Hats-balaclavas",
                  slug: "beanies-fur-Hats-balaclavas",
                },
                {
                  _id: "439",
                  name: "Belts, Suspenders",
                  parent: "/boy/accessories",
                  level: 3,
                  path: "/boy/accessories/belts-suspenders",
                  slug: "belts-suspenders",
                },
                {
                  _id: "442",
                  name: "Gloves, Mittens",
                  parent: "/boy/accessories",
                  level: 3,
                  path: "/boy/accessories/gloves-mittens",
                  slug: "gloves-mittens",
                },
                {
                  _id: "8",
                  name: "Hats, Caps",
                  parent: "/boy/accessories",
                  level: 3,
                  path: "/boy/accessories/caps",
                  slug: "caps",
                },
                {
                  _id: "440",
                  name: "Scarves, Headscarves",
                  parent: "/boy/accessories",
                  level: 3,
                  path: "/boy/accessories/scarves-headscarves",
                  slug: "scarves-headscarves",
                },
                {
                  _id: "446",
                  name: "Schoolbags",
                  parent: "/boy/accessories",
                  level: 3,
                  path: "/boy/accessories/schoolbags",
                  slug: "schoolbags",
                },
                {
                  _id: "434",
                  name: "Sunglasses",
                  parent: "/boy/accessories",
                  level: 3,
                  path: "/boy/accessories/sunglasses",
                  slug: "sunglasses",
                },
                {
                  _id: "448",
                  name: "Ties, Bow Ties",
                  parent: "/boy/accessories",
                  level: 3,
                  path: "/boy/accessories/ties-bow-ties",
                  slug: "ties-bow-ties",
                },
              ],
            },
          ],
        },
        {
          _id: "1",
          name: "Baby",
          parent: "/",
          level: 1,
          path: "/baby",
          slug: "baby",
          children: [
            {
              _id: "254",
              name: "Clothing",
              parent: "/baby",
              level: 2,
              path: "/baby/clothing",
              slug: "clothing",
              children: [
                {
                  _id: "9515",
                  name: "Bloomers",
                  parent: "/baby/clothing",
                  level: 3,
                  path: "/baby/clothing/bloomers",
                  slug: "bloomers",
                },
                {
                  _id: "40",
                  name: "Bodysuits",
                  parent: "/baby/clothing",
                  level: 3,
                  path: "/baby/clothing/bodysuits",
                  slug: "bodysuits",
                },
                {
                  _id: "121",
                  name: "Cardigans",
                  parent: "/baby/clothing",
                  level: 3,
                  path: "/baby/clothing/cardigans",
                  slug: "cardigans",
                },
                {
                  _id: "96",
                  name: "Coats Jackets",
                  parent: "/baby/clothing",
                  level: 3,
                  path: "/baby/clothing/coats-jackets",
                  slug: "coats-jackets",
                },
                {
                  _id: "46",
                  name: "Dresses",
                  parent: "/baby/clothing",
                  level: 3,
                  path: "/baby/clothing/dresses",
                  slug: "dresses",
                },
                {
                  _id: "152",
                  name: "Jeans",
                  parent: "/baby/clothing",
                  level: 3,
                  path: "/baby/clothing/jeans",
                  slug: "jeans",
                },
                {
                  _id: "143",
                  name: "Jumpsuits",
                  parent: "/baby/clothing",
                  level: 3,
                  path: "/baby/clothing/jumpsuits",
                  slug: "jumpsuits",
                },
                {
                  _id: "9536",
                  name: "Leggings",
                  parent: "/baby/clothing",
                  level: 3,
                  path: "/baby/clothing/leggings",
                  slug: "leggings",
                },
                {
                  _id: "146",
                  name: "Outfit-sets",
                  parent: "/baby/clothing",
                  level: 3,
                  path: "/baby/clothing/outfit-sets",
                  slug: "outfit-sets",
                },
                {
                  _id: "158",
                  name: "Overalls",
                  parent: "/baby/clothing",
                  level: 3,
                  path: "/baby/clothing/overalls",
                  slug: "overalls",
                },
                {
                  _id: "90",
                  name: "Pajamas",
                  parent: "/baby/clothing",
                  level: 3,
                  path: "/baby/clothing/pajamas-for-babies",
                  slug: "pajamas-for-babies",
                },
                {
                  _id: "65",
                  name: "Pants",
                  parent: "/baby/clothing",
                  level: 3,
                  path: "/baby/clothing/pants",
                  slug: "pants",
                },
                {
                  _id: "9533",
                  name: "Pramsuits",
                  parent: "/baby/clothing",
                  level: 3,
                  path: "/baby/clothing/pramsuits",
                  slug: "pramsuits",
                },
                {
                  _id: "148",
                  name: "Shirts and Blouses",
                  parent: "/baby/clothing",
                  level: 3,
                  path: "/baby/clothing/shirts-and-blouses",
                  slug: "shirts-and-blouses",
                },
                {
                  _id: "130",
                  name: "Shirts, Blouses",
                  parent: "/baby/clothing",
                  level: 3,
                  path: "/baby/clothing/shirts-blouses",
                  slug: "shirts-blouses",
                },
                {
                  _id: "171",
                  name: "Shorts",
                  parent: "/baby/clothing",
                  level: 3,
                  path: "/baby/clothing/shorts",
                  slug: "shorts",
                },
                {
                  _id: "133",
                  name: "Ski",
                  parent: "/baby/clothing",
                  level: 3,
                  path: "/baby/clothing/ski",
                  slug: "ski",
                },
                {
                  _id: "161",
                  name: "Skirts",
                  parent: "/baby/clothing",
                  level: 3,
                  path: "/baby/clothing/skirts",
                  slug: "skirts",
                },
                {
                  _id: "9516",
                  name: "Socks",
                  parent: "/baby/clothing",
                  level: 3,
                  path: "/baby/clothing/socks",
                  slug: "socks",
                },
                {
                  _id: "8855",
                  name: "Sweaters",
                  parent: "/baby/clothing",
                  level: 3,
                  path: "/baby/clothing/sweaters",
                  slug: "sweaters",
                },
                {
                  _id: "127",
                  name: "Sweatpants",
                  parent: "/baby/clothing",
                  level: 3,
                  path: "/baby/clothing/sweatpants",
                  slug: "sweatpants",
                },
                {
                  _id: "60",
                  name: "Sweatshirts",
                  parent: "/baby/clothing",
                  level: 3,
                  path: "/baby/clothing/sweatshirts",
                  slug: "sweatshirts",
                },
                {
                  _id: "138",
                  name: "Swimsuits",
                  parent: "/baby/clothing",
                  level: 3,
                  path: "/baby/clothing/swimsuits",
                  slug: "swimsuits",
                },
                {
                  _id: "113",
                  name: "T-shirts",
                  parent: "/baby/clothing",
                  level: 3,
                  path: "/baby/clothing/t-shirts",
                  slug: "t-shirts",
                },
                {
                  _id: "9518",
                  name: "Tights",
                  parent: "/baby/clothing",
                  level: 3,
                  path: "/baby/clothing/tights",
                  slug: "tights",
                },
              ],
            },
            {
              _id: "21",
              name: "Shoes",
              parent: "/baby",
              level: 2,
              path: "/baby/shoes",
              slug: "shoes",
              children: [
                {
                  _id: "26",
                  name: "Boots, Booties",
                  parent: "/baby/shoes",
                  level: 3,
                  path: "/baby/shoes/boots-booties",
                  slug: "boots-booties",
                },
                {
                  _id: "22",
                  name: "Essentials",
                  parent: "/baby/shoes",
                  level: 3,
                  path: "/baby/shoes/essentials",
                  slug: "essentials",
                },
                {
                  _id: "23",
                  name: "First Steps",
                  parent: "/baby/shoes",
                  level: 3,
                  path: "/baby/shoes/first-steps",
                  slug: "first-steps",
                },
                {
                  _id: "32",
                  name: "Flats",
                  parent: "/baby/shoes",
                  level: 3,
                  path: "/baby/shoes/flats",
                  slug: "flats",
                },
                {
                  _id: "25",
                  name: "Rain Boots",
                  parent: "/baby/shoes",
                  level: 3,
                  path: "/baby/shoes/rain-boots",
                  slug: "rain-boots",
                },
                {
                  _id: "33",
                  name: "Sandals",
                  parent: "/baby/shoes",
                  level: 3,
                  path: "/baby/shoes/sandals",
                  slug: "sandals",
                },
                {
                  _id: "27",
                  name: "Slippers",
                  parent: "/baby/shoes",
                  level: 3,
                  path: "/baby/shoes/slippers",
                  slug: "slippers",
                },
                {
                  _id: "24",
                  name: "Sneakers",
                  parent: "/baby/shoes",
                  level: 3,
                  path: "/baby/shoes/sneakers",
                  slug: "sneakers",
                },
              ],
            },
            {
              _id: "75",
              name: "Accessories",
              parent: "/baby",
              level: 2,
              path: "/baby/accessories",
              slug: "accessories",
              children: [
                {
                  _id: "78",
                  name: "Beanies, Fur Hats, Balaclavas",
                  parent: "/baby/accessories",
                  level: 3,
                  path: "/baby/accessories/beanies-fur-hats-balaclavas",
                  slug: "beanies-fur-hats-balaclavas",
                },
                {
                  _id: "81",
                  name: "Collars, bows",
                  parent: "/baby/accessories",
                  level: 3,
                  path: "/baby/accessories/collars-bows",
                  slug: "collars-bows",
                },
                {
                  _id: "88",
                  name: "Gloves, Mittens",
                  parent: "/baby/accessories",
                  level: 3,
                  path: "/baby/accessories/gloves-mittens",
                  slug: "gloves-mittens",
                },
                {
                  _id: "83",
                  name: "Hair Accessories",
                  parent: "/baby/accessories",
                  level: 3,
                  path: "/baby/accessories/hair-accessories",
                  slug: "hair-accessories",
                },
                {
                  _id: "89",
                  name: "Hats, Caps",
                  parent: "/baby/accessories",
                  level: 3,
                  path: "/baby/accessories/hats-and-berets",
                  slug: "hats-and-berets",
                },
                {
                  _id: "76",
                  name: "Scarves, Headscarves",
                  parent: "/baby/accessories",
                  level: 3,
                  path: "/baby/accessories/scarves-headscarves",
                  slug: "scarves-headscarves",
                },
                {
                  _id: "79",
                  name: "Sunglasses",
                  parent: "/baby/accessories",
                  level: 3,
                  path: "/baby/accessories/sunglasses",
                  slug: "sunglasses",
                },
                {
                  _id: "85",
                  name: "Ties, Bow Ties",
                  parent: "/baby/accessories",
                  level: 3,
                  path: "/baby/accessories/ties-bow-ties",
                  slug: "ties-bow-ties",
                },
                {
                  _id: "77",
                  name: "Toilet Bags",
                  parent: "/baby/accessories",
                  level: 3,
                  path: "/baby/accessories/toilet-bags",
                  slug: "toilet-bags",
                },
              ],
            },
            {
              _id: "2",
              name: "Nursery",
              parent: "/baby",
              level: 2,
              path: "/baby/childcare",
              slug: "childcare",
              children: [
                {
                  _id: "4",
                  name: "Angel Wings",
                  parent: "/baby/childcare",
                  level: 3,
                  path: "/baby/childcare/angel-wings",
                  slug: "angel-wings",
                },
                {
                  _id: "17",
                  name: "Baby Tableware",
                  parent: "/baby/childcare",
                  level: 3,
                  path: "/baby/childcare/baby/childcare-tableware",
                  slug: "baby-tableware",
                },
                {
                  _id: "15",
                  name: "Bath Wraps",
                  parent: "/baby/childcare",
                  level: 3,
                  path: "/baby/childcare/bath-wraps",
                  slug: "bath-wraps",
                },
                {
                  _id: "7",
                  name: "Bed Linen",
                  parent: "/baby/childcare",
                  level: 3,
                  path: "/baby/childcare/bed-linen",
                  slug: "bed-linen",
                },
                {
                  _id: "37",
                  name: "Bibs",
                  parent: "/baby/childcare",
                  level: 3,
                  path: "/baby/childcare/bibs",
                  slug: "bibs",
                },
                {
                  _id: "11",
                  name: "Blankets, Throws",
                  parent: "/baby/childcare",
                  level: 3,
                  path: "/baby/childcare/blankets-throws",
                  slug: "blankets-throws",
                },
                {
                  _id: "12",
                  name: "Brushes and Combs",
                  parent: "/baby/childcare",
                  level: 3,
                  path: "/baby/childcare/brushes-and-combs",
                  slug: "brushes-and-combs",
                },
                {
                  _id: "6",
                  name: "Changing Mats",
                  parent: "/baby/childcare",
                  level: 3,
                  path: "/baby/childcare/changing-mats",
                  slug: "changing-mats",
                },
                {
                  _id: "16",
                  name: "Diaper Bags",
                  parent: "/baby/childcare",
                  level: 3,
                  path: "/baby/childcare/diaper-bags",
                  slug: "diaper-bags",
                },
                {
                  _id: "20",
                  name: "Health Book Protectors",
                  parent: "/baby/childcare",
                  level: 3,
                  path: "/baby/childcare/health-book-protectors",
                  slug: "health-book-protectors",
                },
                {
                  _id: "5",
                  name: "Sleep sacks",
                  parent: "/baby/childcare",
                  level: 3,
                  path: "/baby/childcare/sleep-sacks",
                  slug: "sleep-sacks",
                },
                {
                  _id: "9",
                  name: "Soft Toys, Comfort Blankets",
                  parent: "/baby/childcare",
                  level: 3,
                  path: "/baby/childcare/soft-toys-comfort",
                  slug: "soft-toys-comfort",
                },
                {
                  _id: "13",
                  name: "Swaddles",
                  parent: "/baby/childcare",
                  level: 3,
                  path: "/baby/childcare/swaddles",
                  slug: "swaddles",
                },
                {
                  _id: "10",
                  name: "Toiletry Bags",
                  parent: "/baby/childcare",
                  level: 3,
                  path: "/baby/childcare/toiletry-bags",
                  slug: "toiletry-bags",
                },
              ],
            },
          ],
        },
        {
          _id: "8836",
          name: "Designers",
          parent: "/",
          level: 1,
          path: "/designers",
          slug: "designers",
          children: [
            {
              _id: "8837",
              name: "All Designers A-Z",
              parent: "/designers",
              level: 2,
              path: "/designers/a-z",
              slug: "a-z",
              children: [
                {
                  _id: "8890",
                  name: "Billieblusht",
                  parent: "/designers/a-z",
                  level: 3,
                  path: "/designers/a-z/billieblusht",
                  slug: "billieblusht",
                },
                {
                  _id: "8845",
                  name: "Bonpoint",
                  parent: "/designers/a-z",
                  level: 3,
                  path: "/designers/a-z/bonpoint",
                  slug: "bonpoint",
                },
                {
                  _id: "8895",
                  name: "Boss",
                  parent: "/designers/a-z",
                  level: 3,
                  path: "/designers/a-z/boss",
                  slug: "boss",
                },
                {
                  _id: "8833",
                  name: "Burberry",
                  parent: "/designers/a-z",
                  level: 3,
                  path: "/designers/a-z/burberry",
                  slug: "burberry",
                },
                {
                  _id: "8843",
                  name: "Chloé",
                  parent: "/designers/a-z",
                  level: 3,
                  path: "/designers/a-z/chloe",
                  slug: "chloe",
                },
                {
                  _id: "8835",
                  name: "Dolce & gabbana",
                  parent: "/designers/a-z",
                  level: 3,
                  path: "/designers/a-z/dolce-gabbana",
                  slug: "dolce-gabbana",
                },
                {
                  _id: "8888",
                  name: "Dsquared2",
                  parent: "/designers/a-z",
                  level: 3,
                  path: "/designers/a-z/dsquared2",
                  slug: "dsquared2",
                },
                {
                  _id: "8885",
                  name: "Golden Goose",
                  parent: "/designers/a-z",
                  level: 3,
                  path: "/designers/a-z/Golden-goose",
                  slug: "Golden-goose",
                },
                {
                  _id: "8807",
                  name: "Gucci",
                  parent: "/designers/a-z",
                  level: 3,
                  path: "/designers/a-z/gucci",
                  slug: "gucci",
                },
                {
                  _id: "8892",
                  name: "Ikks",
                  parent: "/designers/a-z",
                  level: 3,
                  path: "/designers/a-z/ikks",
                  slug: "ikks",
                },
                {
                  _id: "8899",
                  name: "Il Gufo",
                  parent: "/designers/a-z",
                  level: 3,
                  path: "/designers/a-z/il-gufo",
                  slug: "il-gufo",
                },
                {
                  _id: "8874",
                  name: "Jacadi",
                  parent: "/designers/a-z",
                  level: 3,
                  path: "/designers/a-z/jacadi",
                  slug: "jacadi",
                },
                {
                  _id: "8818",
                  name: "Karl Lagerfeld K_ids",
                  parent: "/designers/a-z",
                  level: 3,
                  path: "/designers/a-z/karl-lagerfeld-k_ids",
                  slug: "karl-lagerfeld-k_ids",
                },
                {
                  _id: "8812",
                  name: "Kenzo K_ids",
                  parent: "/designers/a-z",
                  level: 3,
                  path: "/designers/a-z/kenzo-k_ids",
                  slug: "kenzo-k_ids",
                },
                {
                  _id: "8887",
                  name: "Les Coyotes De Paris",
                  parent: "/designers/a-z",
                  level: 3,
                  path: "/designers/a-z/les-coyotes-de-paris",
                  slug: "les-coyotes-de-paris",
                },
                {
                  _id: "8852",
                  name: "Mayoral",
                  parent: "/designers/a-z",
                  level: 3,
                  path: "/designers/a-z/mayoral",
                  slug: "mayoral",
                },
                {
                  _id: "8884",
                  name: "Molo",
                  parent: "/designers/a-z",
                  level: 3,
                  path: "/designers/a-z/molo",
                  slug: "molo",
                },
                {
                  _id: "8810",
                  name: "Moncler",
                  parent: "/designers/a-z",
                  level: 3,
                  path: "/designers/a-z/moncler",
                  slug: "moncler",
                },
                {
                  _id: "8886",
                  name: "Monnalisa",
                  parent: "/designers/a-z",
                  level: 3,
                  path: "/designers/a-z/monnalisa",
                  slug: "monnalisa",
                },
                {
                  _id: "3",
                  name: "Paade Mode",
                  parent: "/designers/a-z",
                  level: 3,
                  path: "/designers/a-z/paade-mode",
                  slug: "paade-mode",
                },
                {
                  _id: "8891",
                  name: "Paul Smith Junior",
                  parent: "/designers/a-z",
                  level: 3,
                  path: "/designers/a-z/paul-smith-junior",
                  slug: "paul-smith-junior",
                },
                {
                  _id: "8877",
                  name: "Perfect Moment",
                  parent: "/designers/a-z",
                  level: 3,
                  path: "/designers/a-z/perfect-moment",
                  slug: "perfect-moment",
                },
                {
                  _id: "8808",
                  name: "Petit Bateau",
                  parent: "/designers/a-z",
                  level: 3,
                  path: "/designers/a-z/petit-bateau",
                  slug: "petit-bateau",
                },
                {
                  _id: "8876",
                  name: "Pom D'api",
                  parent: "/designers/a-z",
                  level: 3,
                  path: "/designers/a-z/pom-d-api",
                  slug: "pom-d-api",
                },
              ],
            },
            {
              _id: "8893",
              name: "Top Designers",
              parent: "/designers",
              level: 2,
              path: "/designers/top",
              slug: "top",
              children: [
                {
                  _id: "8894",
                  name: "Puma",
                  parent: "/designers/top",
                  level: 3,
                  path: "/designers/top/puma",
                  slug: "puma",
                },
                {
                  _id: "8839",
                  name: "Ralph Lauren",
                  parent: "/designers/top",
                  level: 3,
                  path: "/designers/top/ralph-lauren",
                  slug: "ralph-lauren",
                },
                {
                  _id: "8869",
                  name: "Scotch & Soda",
                  parent: "/designers/top",
                  level: 3,
                  path: "/designers/top/scotch-soda",
                  slug: "scotch-soda",
                },
                {
                  _id: "8873",
                  name: "Sonia Rykiel Paris",
                  parent: "/designers/top",
                  level: 3,
                  path: "/designers/top/sonia-rykiel-paris",
                  slug: "sonia-rykiel-paris",
                },
                {
                  _id: "8849",
                  name: "Stella Mccartney K_ids",
                  parent: "/designers/top",
                  level: 3,
                  path: "/designers/top/stella-mccartney-k_ids",
                  slug: "stella-mccartney-k_ids",
                },
                {
                  _id: "8848",
                  name: "Tartine Et Chocolat",
                  parent: "/designers/top",
                  level: 3,
                  path: "/designers/top/tartine-et-chocolat",
                  slug: "tartine-et-chocolat",
                },
                {
                  _id: "8898",
                  name: "The Marc Jacobs",
                  parent: "/designers/top",
                  level: 3,
                  path: "/designers/top/the-marc-jacobs",
                  slug: "the-marc-jacobs",
                },
                {
                  _id: "8805",
                  name: "Tommy Hilfiger",
                  parent: "/designers/top",
                  level: 3,
                  path: "/designers/top/tommy-hilfiger",
                  slug: "tommy-hilfiger",
                },
                {
                  _id: "8831",
                  name: "Versace",
                  parent: "/designers/top",
                  level: 3,
                  path: "/designers/top/versace",
                  slug: "versace",
                },
                {
                  _id: "8850",
                  name: "Young Soles",
                  parent: "/designers/top",
                  level: 3,
                  path: "/designers/top/young-soles",
                  slug: "young-soles",
                },
                {
                  _id: "8889",
                  name: "Zadig Et Voltaire",
                  parent: "/designers/top",
                  level: 3,
                  path: "/designers/top/zadig-voltaire",
                  slug: "zadig-voltaire",
                },
              ],
            },
          ],
        },
      ],
    };
  },
};

export default fetchCommon;
